### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by arozehnal** [brodmo/spotify-folders-backup#1]
python src/main.py
Traceback (most recent call last):
  File "src/main.py", line 9, in <module>
    from model import Folder, SongCollection
  File "f:\Ex\Python\roscripts\spotify\spotify-folders-backup\src\model.py", line 30, in <module>
    class Folder(SongCollection):
  File "f:\Ex\Python\roscripts\spotify\spotify-folders-backup\src\model.py", line 32, in Folder
    contents: list[SongCollection]
TypeError: 'type' object is not subscriptable

Windows 10 / Python 3.8.5

**Comment by brodmo** [comment]
You need Python 3.9 or later, adding this to the README
